language: python
cache: pip
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database django_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
jobs:
  include:
    - stage: test
      script:
        - python manage.py test main.tests
      env:
        global:
          - POSTGRES_DB=django_test
          - POSTGRES_USER=postgres
          - POSTGRES_PASS=
          - DJANGO_SETTINGS_MODULE=noel.settings
    - stage: build
      script:
        - make docker-build
services:
  - postgresql
  - redis-server
notifications:
  email:
    on_failure: never
    on_success: never
branches:
  only:
    - master